name: Sonar-Check && Build/Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: wrkz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  sonar-check:
    runs-on: wrkz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip (required for SonarQube scanner)
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: SonarQube Scan (3tier)
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=3tier-app
            -Dsonar.projectName=3tier-app
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Check Java version
        run: java -version

      - name: Push Docker image
        run: docker push iscanprint/3tier:3.1

      - name: Logout from Docker Hub
        run: docker logout
