name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Use Java 17 to match your pom.xml configuration
        distribution: 'temurin' # Use 'temurin' or another JDK distribution

    - name: Check Java version
      run: java -version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t iscanprint/3tier:3.1 .

    - name: Push Docker image
      run: |
        docker push iscanprint/3tier:3.1

    - name: Logout from Docker Hub
      run: docker logout
